version: "3.9"

services:
  backend:
    build:
      context: ./MathOperationsAPI
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: mathoperations-api

  frontend:
    build:
      context: ./MathOperationsFront
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    container_name: mathoperations-frontend
